ci: add composite actions for image prepare & build
Signed-off-by: Devin Buhl <devin@buhl.casa>

diff --git a/.github/workflows/pull-request.yaml b/.github/workflows/pull-request.yaml
--- a/.github/workflows/pull-request.yaml
+++ b/.github/workflows/pull-request.yaml
@@ -51,15 +51,11 @@ jobs:
           app: ${{ matrix.app }}
 
   build:
-    name: Build (${{ matrix.app }}-${{ matrix.platform }})
+    name: Build (${{ needs.prepare.outputs.app }}-${{ matrix.platform }})
     needs: ["prepare"]
     strategy:
       matrix:
-        app:
-          - ${{ needs.prepare.outputs.app }}
-        version:
-          - ${{ needs.prepare.outputs.version }}
-        platform: ${{ fromJson(needs.prepare.outputs.platforms) }}
+        platform: ${{ fromJSON(needs.prepare.outputs.platforms) }}
     runs-on: ${{ startsWith(matrix.platform, 'linux/arm') && 'ubuntu-24.04-arm' || 'ubuntu-latest' }}
     steps:
       - name: Checkout
@@ -69,28 +65,27 @@ jobs:
         id: build
         uses: ./.github/actions/container-build
         with:
-          app: ${{ matrix.app }}
+          app: ${{ needs.prepare.outputs.app }}
           platform: ${{ matrix.platform }}
-          release: false
-          version: ${{ matrix.version }}
+          version: ${{ needs.prepare.outputs.version }}
 
       - name: Test Container
         uses: ./.github/actions/container-tests
         with:
-          app: ${{ matrix.app }}
-          image: ${{ fromJSON(steps.build.outputs.metadata).image['containerimage.config.digest'] }}
+          app: ${{ needs.prepare.outputs.app }}
+          image: ${{ steps.build.outputs.local-digest }}
           token: ${{ github.token }}
 
-  status:
-    if: ${{ !cancelled() }}
-    needs: ["filter", "prepare", "build"]
-    name: Build Success
-    runs-on: ubuntu-latest
-    steps:
-      - name: Any jobs failed?
-        if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
+  # status:
+  #   if: ${{ !cancelled() }}
+  #   needs: ["filter", "prepare", "build"]
+  #   name: Build Success
+  #   runs-on: ubuntu-latest
+  #   steps:
+  #     - name: Any jobs failed?
+  #       if: ${{ contains(needs.*.result, 'failure') }}
+  #       run: exit 1
 
-      - name: All jobs passed or skipped?
-        if: ${{ !(contains(needs.*.result, 'failure')) }}
-        run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
+  #     - name: All jobs passed or skipped?
+  #       if: ${{ !(contains(needs.*.result, 'failure')) }}
+  #       run: echo "All jobs passed or skipped" && echo "${{ toJSON(needs.*.result) }}"
