ci: add method to create a release on new chart
Signed-off-by: Devin Buhl <devin@buhl.casa>

diff --git a/.github/workflows/retry-release.yaml b/.github/workflows/retry-release.yaml
--- a/.github/workflows/retry-release.yaml
+++ b/.github/workflows/retry-release.yaml
@@ -25,10 +25,10 @@ jobs:
     if: ${{ needs.apps.outputs.apps != '[]' }}
     name: Retry Release
     runs-on: ubuntu-latest
-    needs: apps
+    needs: ["apps"]
     strategy:
       matrix:
-        app: ${{ fromJSON(needs.apps.outputs.apps) }}
+        name: ${{ fromJSON(needs.apps.outputs.apps) }}
       max-parallel: 4
       fail-fast: false
     steps:
@@ -59,17 +59,17 @@ jobs:
         id: bake-options
         uses: ./.github/actions/bake-options
         with:
-          app: ${{ matrix.app }}
+          app: ${{ matrix.name }}
 
       - name: Get Container Registry Version
         id: registry
         env:
           GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
         run: |
-          if ! version=$(regctl image inspect ghcr.io/${{ steps.vars.outputs.repository-owner }}/${{ matrix.app }}:rolling \
+          if ! version=$(regctl image inspect ghcr.io/${{ steps.vars.outputs.repository-owner }}/${{ matrix.name }}:rolling \
               | jq --raw-output '.config.Labels["org.opencontainers.image.version"]' 2>/dev/null) || [[ -z "${version}" ]];
           then
-              echo "Failed to get registry version for ${{ matrix.app }}"
+              echo "Failed to get registry version for ${{ matrix.name }}"
               exit 1
           fi
           echo "version=${version}" >> $GITHUB_OUTPUT
@@ -81,7 +81,7 @@ jobs:
         run: |
           gh workflow run release.yaml \
               --repo ${{ github.repository }} \
-              -f app=${{ matrix.app }} \
+              -f app=${{ matrix.name }} \
               -f release=true
 
           {
@@ -89,5 +89,5 @@ jobs:
               echo
               echo '| Container Name | Actual Version | Expected Version |'
               echo '|----------------|------------------|----------------|'
-              echo '| `${{ matrix.app }}` | `${{ steps.registry.outputs.version }}` | `${{ steps.bake-options.outputs.version }}` |'
+              echo '| `${{ matrix.name }}` | `${{ steps.registry.outputs.version }}` | `${{ steps.bake-options.outputs.version }}` |'
           } >> $GITHUB_STEP_SUMMARY
